### ISSUE TITLE
Environment variable

### ISSUE THREAD

**Issue by onemanstartup** [nicolai86/ansible-rails-deployment#12]
Please check my fork https://github.com/onemanstartup/ansible-rails-deployment i made changes introducing rails_environment variable which can be merged if you have settings hash_behaviour=merge in ansible, that way you don't have to store passwords in files.
PS. I still can't figure out how to securely pass them(http://stackoverflow.com/questions/27058090/secure-environments-no-log-in-ansible) but anyway.

**Comment by nicolai86** [comment]
An easy way to work with passwords would be to use the ansible vaults. You'll basically add an encrypted file to your repo, which ansible will decrypt on the fly and add all variables defined in the file.

See http://docs.ansible.com/playbooks_vault.html for more details about the vaults. Does that help?

**Comment by onemanstartup** [comment]
Actually I forgot what is really I tried to solve by making changes, but ansible vaults doesn't solve problem when you run deploy and use ENV variables. When you run playbook with -vv you can see decrypted variables.

**Comment by nicolai86** [comment]
Do you want to hide the secrets from the person deploying?

**Comment by onemanstartup** [comment]
Yeah.

**Comment by nicolai86** [comment]
Interesting use case, but difficult to make work with ansible. I guess the best way around this would be to wrap ansible execution in a service, and all the users can do is to tell the service to trigger ansible. 

This way you can use sensitive informations in ansible without exposing them.

Anyways, I've just released v0.8 which incooperates the ability to merge environment variables to address the original issue.

See https://github.com/nicolai86/ansible-rails-deployment/commit/2645bb25a21863f73367505026518bbb4fd0d008

**Comment by nicolai86** [comment]
Please re-open if v0.8 does not solve the original issue
